name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          browser: chrome
        env:
          CYPRESS_baseUrl: http://localhost:8080/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v2
